[theme]
base="light"
backgroundColor="#ffffff"
secondaryBackgroundColor="#cdddd0ff"
primaryColor="#adde2f"

[theme.sidebar]

# Background color of the app.
backgroundColor = "#032313"
# Background color used for most interactive widgets.
secondaryBackgroundColor = "#adde2f"

